scoring_demo/global.R
scoring_demo/server.R
scoring_demo/ui.R

Compute column score by passing in max or median aggregate method

---

scoring_demo/global.R
scoring_demo/server.R
scoring_demo/ui.R

Link weighting/threshold with app

---

schema/output-schema.json

Update schema based on new changes

---

workflow/docker_agent_workflow.cwl
workflow/docker_agent_workflow.yaml
workflow/run_docker.cwl
workflow/run_docker.py
workflow/score.cwl
workflow/validate.cwl

* Give permission to log files for admins
* update ChallengeWorkflowTemplate version

Update CWL workflow and tools

---

schema/validate.py
workflow/docker_agent_workflow.cwl
workflow/run_docker.cwl
workflow/run_docker.py

Scatter model across 4 datasets

---

workflow/docker_agent_workflow.cwl

Set dataset parameter as workflow default input

---

R/baseline_annotator.R
R/json_display.R
R/parsing.R
R/scoring.R
schema/output-schema.json

Also update various pieces of R code so that annotation JSON files are read and written consistently across various tasks.

Fix JSON schema for submission output files

---

R/baseline_annotator.R
R/parsing.R
R/scoring.R
schema/output-schema.json
schema/validate.py

More updates to the schema, this time with improvements to some of the field names as well.

Schema fixes

---

workflow/docker_agent_workflow.cwl
workflow/docker_agent_workflow.yaml
workflow/run_docker.cwl
workflow/run_docker.py

No need to use sub-workflow, just add the default inputs as a workflow input

Fix scattering of dataset variable

---

workflow/docker_agent_workflow.cwl

Use source instead of valueFrom

Fix source

---

workflow/run_docker.py

limit to 6g

---

schema/validate.py

This will allow participants to debug

Add in dataset name along with the invalid errors

---

.gitignore
R/baseline_annotator.R
README.md
baseline_demo/baseline_demo.Rmd

Hotfix scoring baseline updates

---

workflow/docker_agent_workflow.cwl
workflow/get_goldstandard_synid.cwl
workflow/run_docker.py

Update Apollo2 to APOLLO-2, goldstandard files, and leaderboard files location on instance

Fine tune workflow

---

R/scoring.R

This addresses #62 (see discussion in issue for details).

fix bug in value domain scoring logic

---

README.md
renv.lock
renv/.gitignore
renv/activate.R
renv/settings.dcf

Adding `renv` dependency management and some additional instructions to make it easier for users to run the baseline demo.

Baseline setup docs

---

README.md
workflow/calc_weighted_score.cwl
workflow/docker_agent_workflow.cwl

In order to provide a ranking for the leaderboard, @tschaffter suggested doing a weighted average across the dataset scores.  Adding this calculation as a step to the workflow so that it can be done as soon as all scores are received, rather than wait until after the round end.

Weighted average calculation

---

R/baseline_annotator.R
baseline_demo/baseline_demo.Rmd

There's been an update to the caDSR export filename, so updating the model to use the latest name.

Update baseline model

---

workflow/docker_agent_workflow-final.cwl
workflow/run_docker-final.py

- removed scattering steps from workflow
- kept the workflow input, `dataset`, but changed default value to `APOLLO-5`
- replaced `get_goldstandard_id` with a Synapse ID to the goldstandard
- updated `input_dir` from `leaderboard_data` to `final_input`
TODO (after doing some dry runs):
- do not return logs
- do not email score

validation phase workflow

---

workflow/docker_agent_workflow-final.cwl
workflow/run_docker-final.py

update to not store logs and to not send score in email
